### ISSUE TITLE
Masked subset writing not working

### ISSUE THREAD

**Issue by Joeybraspenning** [SWIFTSIM/swiftsimio#108] opened 2022-01-12 13:35 UTC
Writing a masked subset of the snapshot doesn't seem to work.
Below is the error I receive on both cosma and Leiden systems and on several different snapshots and with different python versions.

```>>> filename = "/cosma/home/dp004/dc-kuge1/cosma6data/50Mpc_highres_LH/Sims/39/flamingo_0008.hdf5"
>>> mask = sw.mask(filename)
>>> # load_region is a 3x2 list [[left, right], [bottom, top], [front, back]]
... load_region = [[0, 1], [0, 1], [0, 1]]
>>>
>>> # Constrain the mask
... mask.constrain_spatial(load_region * Mpc)
>>> sw.subset_writer.write_subset('test_subset.hdf5', mask)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cosma/home/dp004/dc-bras1/local_env/lib64/python3.6/site-packages/swiftsimio/subset_writer.py", line 326, in write_subset
    write_datasubset(infile, outfile, mask, find_datasets(infile), list_of_links)
  File "/cosma/home/dp004/dc-bras1/local_env/lib64/python3.6/site-packages/swiftsimio/subset_writer.py", line 268, in write_datasubset
    mask_size = get_dataset_mask(mask, name, suffix="_size")
  File "/cosma/home/dp004/dc-bras1/local_env/lib64/python3.6/site-packages/swiftsimio/subset_writer.py", line 69, in get_dataset_mask
    part_type = [int(x) for x in filter(str.isdigit, dataset_name)][0]
IndexError: list index out of range```

**Comment by bwvdnbro** [comment] 2022-04-20 11:53
I can confirm the problem; tentative fix is in #125.

The problem is the addition of `/Header/PartTypeNames` in https://gitlab.cosma.dur.ac.uk/swift/swiftsim/-/commit/b98c4a46f3c430bde3eeaffe4d63a59e67e8d7ca#ab4dd23845732a3f4a1ba6469826b13249039871, which confuses the loop over `/PartTypeX`. `Names` does not parse as a digit... A proper regular expression might have avoided this problem, but `re` is hard.

**Closed** 2022-05-03 07:04 UTC
Labels: bug
